create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  reference text unique not null,
  full_name text not null,
  phone text not null,
  city text not null,
  district text not null,
  address text not null,
  product text not null,
  request_no text not null check (request_no ~ '^[0-9]{17}$'),
  request_date text not null,
  request_code text not null check (request_code ~ '^[0-9]{3}$'),
  status text not null default 'Yeni',
  created_at timestamptz not null default now()
);
alter table public.orders enable row level security;
-- Sunucu SUPABASE_SECRET_KEY kullandığı için tarayıcıya doğrudan tablo erişimi verilmez.
