create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  product text not null,
  first_name text not null,
  last_name text not null,
  phone text not null,
  city text not null,
  district text not null,
  address text not null,
  qty integer not null default 1 check (qty between 1 and 10),
  request_no text not null check (request_no ~ '^[0-9]{17}$'),
  request_date text not null check (request_date ~ '^[0-9]{2}/[0-9]{2}$'),
  request_code text not null check (request_code ~ '^[0-9]{3}$'),
  status text not null default 'Yeni' check (status in ('Yeni','Onaylandı','Kargolandı','İptal')),
  created_at timestamptz not null default now()
);
alter table public.orders enable row level security;
