create table if not exists public.orders(
 id bigint generated by default as identity primary key,
 product text not null,
 name text not null,
 phone text not null,
 city text not null,
 district text not null,
 address text not null,
 order_reference text,
 status text not null default 'stok_yok',
 created_at timestamptz not null default now()
);

alter table public.orders add column if not exists order_reference text;
alter table public.orders add column if not exists status text not null default 'stok_yok';

-- Eski sürümdeki ödeme bilgisine benzeyen alanlar artık kullanılmıyor.
alter table public.orders alter column request_no drop not null;
alter table public.orders alter column request_date drop not null;
alter table public.orders alter column request_code drop not null;

alter table public.orders enable row level security;

create table if not exists public.site_settings(
 id integer primary key default 1 check(id=1),
 logo_url text,
 product1_image_url text,
 product2_image_url text,
 gift_image_url text,
 updated_at timestamptz default now()
);
alter table public.site_settings enable row level security;
insert into public.site_settings(id) values(1) on conflict(id) do nothing;
insert into storage.buckets(id,name,public) values('site-media','site-media',true)
on conflict(id) do update set public=true;


-- V5.4: müşteri talep tanımlayıcıları (ödeme/kart verisi değildir)
alter table public.orders add column if not exists request_no text;
alter table public.orders add column if not exists request_date text;
alter table public.orders add column if not exists request_code text;
